name: "Setup Build Environment"
description: "Install everything needed to build"

runs:
  using: "composite"
  steps:
  - name: Install dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip
  - name: Install Poetry
    shell: bash
    run: pip install --user poetry
